spring:
  application.name: demo
  profiles.active: dev

server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: on_param
    include-exception: true

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

---
spring:
  application.name: demodev
  profiles: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:accounts_db"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900
  ssl:
    key-store: keystore2.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat

security.require-ssl: true

#debug: true
logging:
  level.root: INFO
  file.name: /tmp/logs/mylog.log


---
spring:
  application.name: demoprod
  profiles: prod
  sql.init.mode: always

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/accounts_db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: account_user
    password: acc123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    defer-datasource-initialization: true

server:
  port: 9943

#debug: true
logging:
  level.root: INFO
  file.name: /tmp/logs/mylog.log
